### ISSUE TITLE
Adopt sidecar

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/fakeiteasy.github.io#22]
See https://sidecar.gitter.im/

Looks interesting. Thoughts?

**Comment by blairconrad** [comment]
Just to make sure I understand, then the Chat button would open Gitter in a side window instead of just navigating to Gitter?

Unless you want to run it in "open by default" mode, I'm not sure of the benefit—by the time someone decides to chat, there's probably not much left for them on fakeiteasy.github.io.
Then again, I see no real harm in it. There's a popout button for people who want to banish fakeiteasy.github.io from the remainder of their screen…

As usual, there's probably some nuance I'm missing. Don't hesitate to enlighten me.

**Comment by adamralph** [comment]
It may indeed not be worth it. I was thinking it might offer a more lightweight path to the chat room (i.e. no extra tab) but indeed, unless there's a compelling reason to stay on the website *whilst* chatting then it may not be worth it.

**Comment by blairconrad** [comment]
There's a very small chance that someone may want to talk about the (minimal) content on the website, but I don't think there's a compelling reason to chat and look at the website.
Close?

**Comment by adamralph** [comment]
OK, agreed. The novelty factor has worn off for me :smile:
